#!/bin/bash

if [ -z "$PYFILE" ]; then
    echo "PYFILE environment variable not set"
    exit 1
fi

if [ ! -f "$PYFILE" ]; then
    echo "$PYFILE not found"
    exit 1
fi

python3 -m compileall "$PYFILE"
